# Site configuration
title: "I-140 Petition Letter for EB1 Extraordinary Ability (EB-1A) category"
description: "A detailed guide and personal journey about the EB-1A petition process. Access DIY packages, criteria details, and more."
email: "easydiyeb1a@gmail.com"
baseurl: "easydiyeb1a" # e.g. /repository-name
url: "https://easydiyeb1a.github.io" 

# Build settings
markdown: kramdown
theme: minima

# Additional details
paypal_email: "easydiyeb1a@gmail.com"

