# Site configuration
title: "I-140 Petition Letter for EB1 Extraordinary Ability (EB-1A) category"
description: "EB1A, DIY, Petition Letter."
email: "easydiyeb1a@gmail.com"
baseurl: "" # e.g. /repository-name
url: "https://easydiyeb1a.github.io" 

exclude: README.md

# Build settings
# theme: jekyll-theme-slate

# Additional details
paypal_email: "easydiyeb1a@gmail.com"

#Google Analytics
google_analytics: true
